version: "3.0"

services:
  url-shortener:
    build: ./
    command: ./wait-for-postgres.sh psql ./url-shortener-app
    ports:
      - 8082:8082
    depends_on:
      - psql
    environment:
      - DB_PASSWORD=qwerty
  psql:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5441:5432