env: "local" #local, dev, prod

postgres:
  username: 'postgres'
  host: 'psql'
  port: '5432'
  dbname: 'postgres'
  sslmode: 'disable'

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"