env: "local" #local, dev, prod

postgres:
  username: 'postgres'
  host: 'localhost'
  port: '5431'
  dbname: 'postgres'
  sslmode: 'disable'

http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "myuser"
  password: "mypass"